### ISSUE TITLE
DMXChannel without Offset breaking parser

### ISSUE THREAD

**Issue by hugoaboud** [jackdpage/python-gdtf#1]
Hi, I'm setting up your library to parse GDTF profiles, however it failed with the following error:

> File "C:\Users\Aboud\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\dmx\pygdtf\__init__.py", line 592, in _read_xml
>   self.offset = [int(i) for i in xml_node.attrib.get('Offset')]
> TypeError: 'NoneType' object is not iterable 

I was testing [this](https://gdtf-share.com/gdtf.php?page=home&manu=Generic&fix=LED%20RGB8&rev=346) FixtureType. I found that the first `DMXChannel` of the file has no `Offset` parameter, since it's zero.

I'm not sure what the standard says about it, so I didn't make a pull request. However, it's an easy fix.
Please let me know what you think it's the best strategy here: reporting the file problem to GDTF-Share, including the fix or both.

```python
offset = xml_node.attrib.get('Offset')
if (offset != None):
    self.offset = [int(i) for i in offset.split(',')]
else:
    self.offset = [0]
```

Also, thank you for the work on this library! It's gonna make life so much easier!

**Comment by jackdpage** [comment]
Hi, sorry if I'm a bit late with this one - I have just pushed a change along these lines

According to the standard, the default value for `Offset` is "None", so I have added this as the fallback value if a value isn't provided. I've tested this with the fixture you've linked. Note I have used the string "None" rather than builtin `None` to keep in line with the documentation they provide

Cheers
